<html>
<head>
<fieldset>
<fieldset>
<fieldset>


    <link rel='stylesheet' type='text/css' media='screen' href='site.css'>
<body style="background-image: url('555.jpg');background-size: cover;">
<input class="variation" id="bluepurple" type="radio" value="1" name="color" checked="checked"/>
<label for="bluepurple"></label>
<input class="variation" id="sunset" type="radio" value="2" name="color"/>
<label for="sunset"></label>
<input class="variation" id="godiva" type="radio" value="3" name="color"/>
<label for="godiva"></label>

<select value="iphone" size="1">
<option value="2018"><a href="222.php">2018</a></option>
 <div class="topnav">
	 		  <a href="ABOUT.php">About</a>
	 	  <a class="active"href="home.php">Home </a>
		  <a href="login admin.php">Login</a>
		  <a href="main.php">display Phones</a>

	</div> 
<table>
<tr>
<td style="color:red">     id</td>
<td style="color:red">    name</td>
<td style="color:red">   address</td>
</tr>
<tr>
<td>1</td>
<td>ashgan</td>
<td> omduramn</td>
</tr>
<table>
<tr>
<td style="color:red">     id</td>
<td style="color:red">    name</td>
<td style="color:red">   address</td>
</tr>
<tr>
<td>1</td>
<td>ashgan</td>
<td> omduramn</td>
</tr>
<body style="background-image: url('CDCD.jpg');background-size: cover;">
<select name="samsung">

<h3><p style="COLOR:purple"> Visit Our Website Via </P></h3>
<IMG SRC="ccc.png" STYLE="width:70PX; height:40PX;">
<IMG SRC="vvv.png" STYLE="width:60PX; height:40PX;">
<IMG SRC="bbb.png" STYLE="width:60PX; height:40PX;">

<p style="COLOR:purple;">< ACTION TEHCNOLGY >></p>

<main "align:center">
	<br><CENTER>
	<h3  style="background-color: YELLOW;"><p style="color: blue">    location   ACTION TEHCNOLGY   Sudan _ Khartoum _ Buildings   </p></h3>
	<br>
	<h3  style="background-color: BLUE;"><p style="color:YELLOW">phones +249958741236  +2496547128745 +2496587412358  </p></h3>
	<br></CENTER>
	<center>
  
<div class="profile__cta"><a style="width:20 hight:50 "  href="welcome 1.php" class="button "> Homepage</a></div>  
</main>
</CENTER>

</fieldset>

</body>
</html>